---
- hosts: borderleaf1-DC1, borderleaf2-DC1
  gather_facts: no
  tasks:
  - name: Register variables
    include_vars:
      file: "{{lookup('env','PWD')}}/vars/underlay-DC1-2.yml"
      name: underlay
  - name: Create Borderleaf underlay configuration for DC1
    template:
      src: "{{lookup('env','PWD')}}/templates/eBGP_Underlay_Leafs.j2"
      dest: "{{lookup('env','PWD')}}/configs/{{inventory_hostname}}_Underlay.cfg"