---
- hosts: spine1-DC2, spine2-DC2, spine3-DC2
  gather_facts: no
  tasks:
  - name: Register variables
    include_vars:
      file: "{{lookup('env','PWD')}}/vars/underlay-DC1-2.yml"
      name: underlay
  - name: Create Spine underlay configuration for DC2
    template:
      src: "{{lookup('env','PWD')}}/templates/eBGP_Underlay_Spines.j2"
      dest: "{{lookup('env','PWD')}}/configs/{{inventory_hostname}}_Underlay.cfg"