---
- hosts: leafs_DC1, leafs_DC2
  gather_facts: no
  tasks:
  - name: Create MLAG config
    template:
      src: "{{lookup('env','PWD')}}/templates/mlag_left.j2"
      src: "{{lookup('env','PWD')}}/templates/mlag_right.j2"
      dest: "{{lookup('env','PWD')}}/configs/{{inventory_hostname}}_mlag.cfg"
  - name: Upload MLAG config
    eos_config:
      src: "{{lookup('env','PWD')}}/configs/{{inventory_hostname}}_mlag.cfg"